spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: board
    password: minmax
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=UTF-8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cors:
    mappings: null
    '[/**]':
      allowed-origins: '*'
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: '*'
      allow-credentials: true
      max-age: 3600
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.project.dto
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8091
  servlet:
    context-path: /project
    session:
      timeout: 3600
logging:
  config: classpath:log4j/log4j2.xml
login:
  list: /check/**
admin:
  list: /cat/**
manager:
  list: /mng/**